import { resourceDirectory, type ResourceMetadata } from './resource-directory';

export type ResourceSection = { id: string; title: string; paragraphs?: string[]; steps?: string[]; bullets?: string[]; table?: { headings: string[]; rows: string[][]; cellLinks?: { row: number; column: number; label: string; href: string }[] }; code?: string; note?: string; links?: { label: string; href: string }[] };
export type ResourceArticle = ResourceMetadata & { sections: ResourceSection[] };
const link = (key: string, label: string) => ({ label, href: `#resource-${key}` });

const resourceContents: { key: string; sections: ResourceSection[] }[] = [
  { key: 'product-documentation', sections: [
    { id: 'start', title: 'Start with the incident lifecycle', paragraphs: ['NexusOps brings monitoring signals, service ownership, response activity and post-incident learning into one workspace. A monitoring tool detects a condition; NexusOps receives its events and coordinates the response. The current application is a browser-based prototype for one organization and one team.', 'Begin with the incident list. An incident connects a service, its linked alerts, an assigned responder and a timeline. Acknowledgement records ownership; resolution records the end of the response.'], links: [link('incident-response', 'Follow the incident response guide'), link('explore-demo', 'Choose your demo role')] },
    { id: 'products', title: 'Four connected product workflows', table: { headings: ['Workflow', 'What it helps you do'], rows: [['Incident Management', 'Review alerts, filter incidents, acknowledge ownership, record notes and resolve with a reason.'], ['On-call & Escalation', 'Plan service coverage and define who should be notified when an incident has not been acknowledged.'], ['AI Investigation & Automation', 'Review evidence and hypotheses, then propose, approve and simulate a guarded runbook action.'], ['Post-Incident Review & Insights', 'Review the response, assign follow-up work and read MTTA/MTTR with their sample counts.']] }, links: [{ label: 'Incident Management', href: '#product-incident-management' }, { label: 'On-call & Escalation', href: '#product-on-call-escalation' }, { label: 'AI & Automation', href: '#product-ai-automation' }, { label: 'Post-Incident Insights', href: '#product-post-incident-insights' }] },
    { id: 'platform', title: 'The platform behind each workflow', bullets: ['Service Catalog: ownership, criticality and directed dependencies provide service context.', 'Monitoring Integrations: the planned intake boundary for authenticated monitoring events; the workspace currently creates local test incidents.', 'Policies & Permissions: roles grant actions; team scope, incident assignment and workflow state decide whether an action is allowed.', 'Audit Trail: records who changed what. Current records are local demo data; durable, append-only storage belongs to the backend design.'], links: [{ label: 'Service Catalog', href: '#platform-service-catalog' }, { label: 'Monitoring Integrations', href: '#platform-monitoring-integrations' }, { label: 'Policies & Permissions', href: '#platform-policies-permissions' }, { label: 'Audit Trail', href: '#platform-audit-trail' }] },
    { id: 'navigation', title: 'Find your way around', paragraphs: ['The workspace navigation adapts to your permissions. Responder accounts start in Incidents; Admin, Manager and Viewer accounts start in Overview. The NexusOps logo returns to that role-specific starting page.', 'The bell opens your personal inbox. Reading a notification does not acknowledge its incident. Profile lets every role update its own personal details, avatar and password.'], note: 'Public Product and Solution pages explain capabilities. These Resources pages explain how to use the current prototype and where its MVP design extends beyond it.', links: [link('roles-permissions', 'Check the role and scope rules'), link('mvp-scope', 'See the implementation boundaries')] },
  ] },
  { key: 'mvp-scope', sections: [
    { id: 'baseline', title: 'A focused operational baseline', paragraphs: ['The MVP covers one organization and one team. Its lifecycle runs from monitoring events through alert deduplication, incident response, controlled automation and post-incident review. Roles are fixed: Account Admin, Team Manager, Responder and Viewer. Incident Commander is assigned on an individual incident.', 'MVP Scope.md defines the backend contracts. The current README and workspace permission map describe the subsequently agreed role rules, including Manager control of schedules, escalation and integrations. The backend role seed still needs to be aligned with those decisions.'] },
    { id: 'availability', title: 'Implementation coverage', table: { headings: ['Area', 'Available in the prototype', 'Backend work defined or still required'], rows: [['Access', 'Demo login, invitations, role changes, profiles and local session invalidation.', 'Protected Admin bootstrap, server sessions, transactional invitation acceptance and server authorization.'], ['Response', 'Shared local incidents, assignments, ACK, notes, manual resolve and personal inbox.', 'Authenticated intake, dedup/grouping, ordered recovery, durable jobs and notification delivery.'], ['On-call', 'Concrete shifts, service coverage and a two-level policy editor.', 'Policy snapshots, durable deadlines, bounded reminders and a final backstop.'], ['AI & automation', 'Sample investigation and approved sandbox simulation.', 'Scoped model tools, immutable evidence/action snapshots, executor reconciliation and durable guards.'], ['Learning', 'PIR editing/review, local audit and timestamp-based analytics.', 'Versioned persistence, approved knowledge indexing and durable audit history.']] } },
    { id: 'invariants', title: 'Rules the complete system must preserve', bullets: ['Deduplicate only OPEN alerts within their integration/service namespace. Group newly created eligible alerts within the same service and configured grouping window.', 'An ordered recovery closes the relevant alert; automatic incident resolution requires every linked alert to be resolved.', 'ACK records the first acknowledgement and cancels pending escalation. Manual resolve requires acknowledgement, permission, assignment and a reason.', 'AI investigation is read-only. Approval is tied to an immutable action snapshot; approval cannot override execution quotas.', 'Post-incident drafts require human review before being treated as approved knowledge. Metrics show a time window and eligible sample count.'] },
    { id: 'outside', title: 'Outside the current baseline', paragraphs: ['Multi-organization tenancy, complex rotating schedules, native mobile apps, provider-backed phone/SMS paging, a custom monitoring platform and autonomous production remediation are not part of this frontend prototype. It does not replace Prometheus, Grafana or another monitoring tool.'], note: 'A working demo screen is evidence of a frontend flow, not proof that its corresponding backend invariant is implemented.', links: [link('api-reference', 'Read the draft API contract'), link('project-changelog', 'See documented project milestones')] },
  ] },
  { key: 'roles-permissions', sections: [
    { id: 'matrix', title: 'Workspace permission matrix', table: { headings: ['Capability', 'Admin', 'Manager', 'Responder', 'Viewer'], rows: [['Read incidents, services, schedules, status and analytics', 'Yes', 'Yes', 'Yes', 'Yes'], ['View People', 'Yes', 'Yes', 'Yes', 'No'], ['Invite users, change roles, disable accounts', 'Yes', 'No', 'No', 'No'], ['Manage services, schedules, escalation, integrations', 'Yes', 'Yes', 'No', 'No'], ['Assign responder / Commander', 'Yes', 'Yes', 'No', 'No'], ['ACK, resolve, notes, AI and automation', 'When assigned', 'Add Responder + assignment', 'When assigned', 'No'], ['Edit PIR draft', 'Yes', 'Yes', 'When assigned', 'No'], ['Review PIR and complete follow-up', 'Yes', 'Yes', 'No', 'No'], ['Read approved / completed PIR', 'Yes', 'Yes', 'Yes', 'Yes'], ['View administrative audit', 'Yes', 'No', 'No', 'No'], ['Edit own profile / avatar / password', 'Yes', 'Yes', 'Yes', 'Yes']] } },
    { id: 'scope', title: 'Role alone does not authorize every action', paragraphs: ['A response action requires its permission, membership in the incident’s team, assignment as responder or Commander, and a valid incident/action state. An Admin also needs incident assignment to perform response actions. A Manager can combine Manager and Responder roles; Viewer is used on its own.', 'A Commander assignment does not grant missing permissions. It identifies the coordination responsibility on a particular incident. All visible means incidents within your readable team scope, not unrestricted access across an organization.'] },
    { id: 'join', title: 'How people join the workspace', steps: ['The first Admin is already seeded in this demo. A production deployment needs a protected bootstrap procedure.', 'An Admin opens People → Invite member, enters the email and assigns roles.', 'The recipient uses Join your team with the matching email, invitation code, name and password. Demo invitations last 72 hours and must be accepted on the same browser/origin that stores them.', 'Resend replaces the old code. Revoke invalidates a pending invitation. Accepted, expired or revoked invitations cannot create another account.'], note: 'The prototype does not send invitation emails. Managers cannot invite users or grant roles; contact an Admin for access changes.' },
    { id: 'changes', title: 'When access changes', paragraphs: ['Role changes and account disabling invalidate existing demo sessions. The last active Admin is protected. Reassign open incidents, future/current shifts and policy targets before removing response responsibilities or disabling an account.', 'The interface and command handlers check permissions locally. Production security requires the same rules on every server request.'], links: [link('help-support', 'Troubleshoot access'), link('explore-demo', 'Explore the role-specific demo')] },
  ] },
  { key: 'api-reference', sections: [
    { id: 'status', title: 'Contract status and authentication', paragraphs: ['This is a design reference from MVP Scope.md, not an available API service. There is no live base URL, API key issuance or Try it out feature. The planned prefix is /api/v1. Monitoring events use an integration credential; management requests use authenticated user access (JWT in the baseline).', 'The complete event intake route and credential header must be finalized with the backend implementation. The example below is a payload illustration and does not make a network request.'] },
    { id: 'payload', title: 'Monitoring event payload', code: '{\n  "eventType": "TRIGGER",\n  "dedupKey": "payments-api:http-5xx",\n  "episodeId": "example-episode-001",\n  "sourceSequence": 101,\n  "timestamp": "2026-10-04T03:42:00Z",\n  "severity": "critical",\n  "summary": "Payment API error rate above threshold"\n}', table: { headings: ['Field', 'Purpose'], rows: [['eventType', 'TRIGGER opens/updates an alert; RESOLVE closes the matching episode.'], ['dedupKey', 'Identifies the alert stream inside the integration/service namespace.'], ['episodeId', 'Identifies an occurrence episode; it is not a request retry key.'], ['sourceSequence', 'Increases across episodes in a stream so stale events can be rejected safely.'], ['timestamp', 'Source event time. Ordering metadata must still be provided.'], ['severity / summary', 'Required for TRIGGER; final accepted severity values belong to the backend schema.']] }, note: 'Use Content-Type: application/json. A RESOLVE includes the same stream/episode identity with a newer sourceSequence. Missing ordering metadata is a validation error.' },
    { id: 'identity', title: 'Retry, deduplication and grouping', bullets: ['Idempotency-Key identifies the same request inside one integration. A matching key/body replays the committed response; a changed body with that key conflicts.', 'dedupKey identifies repeated occurrences of an OPEN alert. A new accepted occurrence can increment its count.', 'Grouping is a separate rule for eligible new alerts in the same service and grouping window. It does not replace either request idempotency or stream identity.'] },
    { id: 'management', title: 'Management contract excerpts', table: { headings: ['Contract', 'Expected behavior'], rows: [['POST /api/v1/runbooks/{id}/execute', '202 returns an actionId. It does not prove execution; an approval gate may still be pending.'], ['GET /api/v1/notifications?after=cursor', 'Catch up on durable inbox notifications after a disconnect.'], ['ACK / resolve mutations', 'Require expectedVersion plus permission, assignment, scope and valid state. Exact routes remain to be finalized.'], ['Approval mutation', 'Requires expectedVersion and snapshotHash. A changed action needs a new approval.']] } },
    { id: 'errors', title: 'Errors and execution boundaries', table: { headings: ['Status', 'Meaning in the draft contract'], rows: [['400', 'Invalid payload or missing required ordering metadata.'], ['409', 'Idempotency body conflict or stale domain version.'], ['429', 'Ingress rate quota exceeded; observe Retry-After.'], ['503', 'Transient contention; observe Retry-After and retry within a bounded policy.']] }, paragraphs: ['Authentication and authorization failures must also be handled by the final server contract. The frontend is not a substitute for this enforcement. Execution quotas, snapshot validation and the circuit breaker are independent of ingress rate limits.'], links: [link('mvp-scope', 'Review MVP boundaries'), link('ai-investigation-automation', 'Understand action approval')] },
  ] },
  { key: 'incident-response', sections: [
    { id: 'before', title: 'Before you begin', paragraphs: ['Use an enabled Responder account, or an Admin/Manager account with the required response permissions. You must be assigned as responder or Commander for the incident. An Admin or Manager can set assignments in incident details.', 'The demo starts with sample incidents. Admins and Managers can also create a local test incident from Integrations after configuring the service, integration and policy.'], links: [link('roles-permissions', 'Check permissions')] },
    { id: 'respond', title: 'Respond to an incident', steps: ['Open Incidents. Use Assigned to me, Commanding or All visible, then narrow by status, service or priority. Open an incident title.', 'Read the linked alerts, service, assigned responder and timeline. Confirm you are acting on the right incident.', 'Select Acknowledge. The state changes from Triggered to Acknowledged and the first ACK time is recorded.', 'Record investigation findings with notes. Where available, request a sample investigation and review its evidence and unconfirmed hypothesis.', 'Once recovery is justified, enter a resolution reason and select Resolve. The local demo closes linked alerts, cancels pending actions and creates a PIR draft.'], note: 'Opening an incident or reading its inbox notification is not ACK. Successful sandbox execution does not automatically resolve the incident.' },
    { id: 'states', title: 'Read the state correctly', table: { headings: ['State or filter', 'Meaning'], rows: [['Open', 'Triggered and Acknowledged incidents together.'], ['Triggered', 'Response has not been acknowledged; the MVP escalation flow can progress.'], ['Acknowledged', 'An authorized responder has accepted ownership; work is still in progress.'], ['Resolved', 'The response has been closed with a reason or, in the full backend design, by valid monitoring recovery.']] } },
    { id: 'blocked', title: 'If an action is unavailable', bullets: ['Check assignment and permissions. Being able to read an incident does not grant response rights.', 'Only Triggered incidents can be acknowledged. Manual resolution requires Acknowledged state and a reason.', 'A resolved incident cannot run a new investigation or automation action in the current demo.', 'For an empty list, clear filters or try All visible. For a new assignment, check the personal inbox.'], links: [link('post-incident-reviews', 'Continue with the post-incident review'), link('help-support', 'Read troubleshooting guidance')] },
  ] },
  { key: 'on-call-operations', sections: [
    { id: 'concepts', title: 'Coverage and escalation answer different questions', paragraphs: ['A schedule shows who covers a service during a time interval. An escalation policy defines notification targets, acknowledgement timeouts, reminders and the final backstop.', 'Admins and Managers configure both. Responders and Viewers can read them. The current local test event selects the first eligible static Level 1 policy target; it does not dynamically look up the on-call calendar.'] },
    { id: 'schedule', title: 'Set up service coverage', steps: ['Open On-call schedule and choose the service, week and timezone view.', 'Create a concrete shift for an eligible responder. Select Primary or Secondary, then enter start and end times.', 'Save the shift and inspect the week view. Use Today and week navigation to review nearby coverage.', 'Check for gaps before the handoff. The editor rejects overlaps in the same service/layer and shifts outside the supported 30-minute to 7-day duration.'], note: 'The current schedule stores concrete shifts. It does not run background rotations or promise daylight-saving-time support.' },
    { id: 'policy', title: 'Configure escalation', steps: ['Open Escalation policies and select the service.', 'Choose eligible responders for Level 1 and Level 2. Set acknowledgement timeouts and bounded reminders.', 'Choose a final backstop, then save. The policy version changes so stale edits can be detected.', 'Use Response preview to read the configured order. An ACK stops pending escalation in the full MVP flow; the last level ends with a single backstop.'] },
    { id: 'test', title: 'Create a local test incident', paragraphs: ['In Integrations, enable the service’s demo integration and save it. Send a test event. The service must be enabled and have a saved policy with an eligible primary target.', 'Check Incidents and then sign in as the assigned responder to see the inbox notification and acknowledge the incident. The test creates local data; no monitoring endpoint, SMS or email is contacted.'], note: 'No autonomous escalation timer currently runs in the workspace. Response preview is a policy explanation, not a live delivery log.', links: [link('incident-response', 'Respond to the test incident'), { label: 'Explore the on-call product', href: '#product-on-call-escalation' }] },
  ] },
  { key: 'ai-investigation-automation', sections: [
    { id: 'investigate', title: 'Read an investigation critically', steps: ['Open an unresolved incident assigned to you with AI_RUN permission.', 'Select Generate sample investigation. Read the linked alert IDs and service context.', 'Separate observed facts from the suggested hypothesis. A nearby deployment may be related, but time proximity alone does not prove causality.', 'Record missing evidence and your next check in the incident notes.'], note: 'The current report is deterministic sample text. No model or retrieval system is called.' },
    { id: 'action', title: 'Walk through the sandbox action', steps: ['Select Propose sample runbook on the incident. The fixed demo runbook inspects service health and starts in PENDING_APPROVAL.', 'Review the proposal. An assigned actor with AUTOMATION_EXECUTE can choose Approve snapshot or Reject.', 'After approval, choose Run sandbox simulation. The local result becomes SUCCEEDED; no shell command or external system is changed.', 'Check the incident timeline. Decide independently whether the incident is ready to resolve.'], note: 'The demo requires approval for every proposal and limits simulations to two per service in 15 minutes. It blocks execution before approval, repeated execution and execution after incident resolution.' },
    { id: 'backend', title: 'The full MVP execution gate', paragraphs: ['The backend design requires per-instance human approval when effective risk is HIGH, the runbook requires approval, or valid pre-authorization is absent. A LOW action can still need approval.', 'The snapshot binds runbook version, target, parameters, risk and evidence. Dispatch revalidates permissions, incident scope/state and the snapshot before reserving a quota slot. The design allows at most two reservations per service/runbook in a sliding 15-minute window. Three consecutive FAILED or UNKNOWN outcomes open a 15-minute circuit breaker.'], note: 'Durable reservations, immutable snapshot hashes and the circuit breaker are backend requirements. The local simulation does not implement all of these guarantees.' },
    { id: 'outcomes', title: 'Handle uncertain outcomes', paragraphs: ['In the complete design, a timeout after dispatch can mean UNKNOWN. Investigate the existing execution outcome instead of blindly retrying a potentially completed action. AI has read-only investigation tools and cannot approve or execute its own proposal.', 'Resolution cancels actions still pending locally. A real backend cancellation cannot undo an external action that has already started.'], links: [link('api-reference', 'Read the action contract'), { label: 'Explore AI & Automation', href: '#product-ai-automation' }] },
  ] },
  { key: 'post-incident-reviews', sections: [
    { id: 'draft', title: 'Prepare a review after resolution', steps: ['Resolve the incident with a meaningful reason. The current demo creates a DRAFT review from that resolution.', 'Open Post-incident reviews. Read Incident evidence and use the timeline to write a clear summary.', 'Record the follow-up action and choose an active owner. An assigned Responder can edit the draft; Admins and Managers can also edit it.', 'Save draft or Submit for review. Include confirmed observations and remaining uncertainty; avoid assigning blame.'], note: 'The current draft starts from the resolution reason. Evidence-backed AI generation is planned in the MVP, not connected in the prototype.' },
    { id: 'review', title: 'Review and close the learning loop', steps: ['A Manager or Admin reads the IN_REVIEW draft and its evidence.', 'Use Request changes to return it to DRAFT, or Approve review when the account is accurate.', 'After approval, the summary, follow-up text and owner are locked in the current UI. Track the recorded follow-up to completion.', 'Mark Follow-up completed when applicable, then Complete review. Viewer accounts can read APPROVED and COMPLETED reviews.'] },
    { id: 'metrics', title: 'Interpret MTTA and MTTR correctly', table: { headings: ['Metric', 'Calculation', 'Eligible records'], rows: [['MTTA', 'Average time from incident creation/trigger to first ACK.', 'Incidents with an ACK timestamp, including those still open.'], ['MTTR', 'Average time from incident creation/trigger to resolution.', 'Resolved incidents, including auto-resolved incidents without ACK in the backend design.']] }, paragraphs: ['Use the selected 24-hour, 7-day or 30-day window and inspect the sample count beside each metric. Missing timestamps are excluded, not counted as zero. MTTA and MTTR can have different denominators.', 'The current demo first selects incidents by creation time within the chosen window. The M7 backend contract instead selects MTTA samples by ACK time and MTTR samples by resolution time. These cohorts can produce different results; backend analytics still needs to implement that contract. A single duration does not establish a trend, and MTTD is outside this MVP.'] },
    { id: 'knowledge', title: 'From review to reusable knowledge', paragraphs: ['The full MVP indexes only approved PIR content into the knowledge base, with source and version provenance. AI-generated drafts cannot approve themselves or overwrite approved human content.', 'Keep conclusions linked to evidence and give follow-up actions a concrete owner. Future responders should be able to distinguish what was confirmed from what remains a hypothesis.'], links: [link('incident-glossary', 'Look up review terminology'), { label: 'Explore post-incident insights', href: '#product-post-incident-insights' }] },
  ] },
  { key: 'incident-glossary', sections: [
    { id: 'terms', title: 'Find a term', paragraphs: ['Search the definitions below or choose a topic. These meanings describe NexusOps; another incident platform may use different states or permission rules.'] },
    { id: 'differences', title: 'Common distinctions', bullets: ['An event is an incoming message; an alert tracks a condition; an incident coordinates a response and can link several alerts.', 'ACK accepts response ownership. Read marks an inbox item as read. Resolve closes the response.', 'A schedule describes coverage. A policy defines escalation targets and deadlines.', 'A role grants a type of action. Assignment and object scope decide where the actor may use it.'], links: [link('incident-response', 'See the terms in a response'), link('roles-permissions', 'Understand access rules')] },
  ] },
  { key: 'explore-demo', sections: [
    { id: 'accounts', title: 'Choose your demo perspective', table: { headings: ['Account', 'What to explore'], rows: [['admin@nexusops.demo', 'People, invitations, access control, configuration and administrative audit.'], ['manager@nexusops.demo', 'Service setup, schedule, policy, integrations, assignments and PIR review.'], ['responder@nexusops.demo', 'Assigned incidents, ACK, notes, sample investigation and sandbox actions.'], ['viewer@nexusops.demo', 'Read-only operational views and approved reviews.'], ['commander@nexusops.demo', 'Combined Manager + Responder; Commander assignment on incident #1048.']] }, paragraphs: ['Open Login, choose a Demo account, use the sample-account fill action and log in. The initial shared sample password is NexusOps@2026. If the account has been modified locally, its updated password and role rules apply.'], links: [{ label: 'Open demo login', href: '#login' }] },
    { id: 'tour', title: 'A practical walkthrough', steps: ['As Manager, inspect Services, Schedule and Escalation policies. Enable a demo integration and send a local test event.', 'Switch to the assigned Responder on the same browser/origin. Open the inbox or incident list, read the context and acknowledge.', 'Add a note, generate a sample investigation, propose a runbook and review the sandbox action.', 'Resolve with a reason and prepare the resulting PIR draft. Submit it for review.', 'Switch to Manager to review, approve and complete the follow-up. Use Viewer to read the approved review, or Admin to inspect the audit.'] },
    { id: 'data', title: 'What happens to demo changes', paragraphs: ['Accounts share local workspace data on the same browser/origin. Logging out removes the session but keeps the data. A different browser, device, port or origin has its own dataset.', 'The demo does not send invitation emails, receive external monitoring webhooks, page phones or execute production commands. Use the sample data to explore permissions and workflow states.'], note: 'There is no Reset sample data control in the current multi-role workspace. Avoid assuming the reset button in older screenshots is available.', links: [link('help-support', 'Get demo help'), link('mvp-scope', 'Review current limits')] },
  ] },
  { key: 'project-changelog', sections: [
    { id: 'current', title: 'Current working update · Resources', paragraphs: ['Audited the Resources library and clarified its MVP v3 reference baseline. Help & Support now routes common issues to the relevant guide and includes a copyable, privacy-conscious issue report template. This entry describes the current working tree and is not a tagged release.'], note: 'This page tracks prototype development. Dates below come from repository commits; they are not production deployment dates.' },
    { id: 'oct04', title: '04 October 2026 · Dashboard', paragraphs: ['Recorded milestone: “Update frontend (Dashboard)”. The current workspace presents role-based operational views. The README documents the available multi-role flows and their local-data limitations.'] },
    { id: 'oct03', title: '03 October 2026 · Product and scheduler interfaces', paragraphs: ['Recorded milestones: “Implement product section” and “Update frontend (Scheduler)”. These mark frontend work on product presentation and scheduling. A scheduler interface does not by itself establish live schedule-based paging.'] },
    { id: 'oct02', title: '02 October 2026 · Frontend foundation', paragraphs: ['Recorded milestones: “Implement Frontend” and “Update Frontend (Profie and Taskbar)”. These entries preserve the repository’s recorded scope without assigning an invented release version.'] },
    { id: 'reading', title: 'Read updates alongside the implementation scope', paragraphs: ['An interface milestone can precede its backend integration. Use MVP Scope to check which behavior is available locally and which contract remains planned. Future entries should identify the actual change, its date and any meaningful limitation.'], links: [link('mvp-scope', 'Read implementation coverage')] },
  ] },
  { key: 'help-support', sections: [
    { id: 'quick', title: 'Find the right next step', paragraphs: ['Start with the symptom below. The linked guides explain the behavior currently available in the NexusOps prototype.'], table: { headings: ['If you need to…', 'Check first', 'Then open'], rows: [['Sign in or accept an invitation', 'Use the invited email and current code; invitations expire after 72 hours and are accepted on the same browser/origin where they were created.', 'Roles & Permissions'], ['Acknowledge or resolve an incident', 'Check your role, team scope, incident assignment and current incident state.', 'Incident Response'], ['Set up coverage or test escalation', 'Confirm the service, saved policy and eligible target. The workspace has no autonomous escalation timer or live paging.', 'On-call Operations'], ['See the same demo changes as a teammate', 'Use the same browser and origin. Demo data is stored locally and is not shared across devices.', 'Explore the Demo'], ['Understand a missing feature', 'Check whether it is prototype behavior, a planned backend contract or outside the MVP.', 'MVP Scope']], cellLinks: [{ row: 0, column: 2, label: 'Roles & Permissions', href: '#resource-roles-permissions' }, { row: 1, column: 2, label: 'Incident Response', href: '#resource-incident-response' }, { row: 2, column: 2, label: 'On-call Operations', href: '#resource-on-call-operations' }, { row: 3, column: 2, label: 'Explore the Demo', href: '#resource-explore-demo' }, { row: 4, column: 2, label: 'MVP Scope', href: '#resource-mvp-scope' }] } },
    { id: 'faq', title: 'Frequently asked questions', paragraphs: ['Expand a question below. The answers apply to the current local prototype.'] },
    { id: 'report', title: 'Prepare a useful, safe issue report', paragraphs: ['For workspace access or membership changes, contact your known workspace Admin using your organization’s existing communication channel. For a reproducible product issue, share the summary below with the project maintainer. Include the page, role, steps, expected result and actual result; a cropped screenshot can help.'], links: [link('roles-permissions', 'Review roles and access'), link('mvp-scope', 'Check prototype boundaries')] },
  ] },
];

export const resourceArticles: ResourceArticle[] = resourceContents.map(content => ({ ...resourceDirectory.find(item => item.key === content.key)!, ...content }));
export const glossary = [
  ['Event', 'Signals', 'A monitoring message describing a trigger or recovery. Repeated events can belong to one alert.'],
  ['Alert', 'Signals', 'A tracked condition in a service. OPEN alerts can be deduplicated; an alert belongs to at most one incident.'],
  ['Incident', 'Response', 'A response record joining service context, linked alerts, assignment and a timeline.'],
  ['Service', 'Signals', 'A system component with ownership, criticality and dependencies, such as payments-api.'],
  ['Integration', 'Signals', 'A service-specific event intake configuration. The current UI uses a local test source.'],
  ['Idempotency-Key', 'Signals', 'A request retry identifier scoped to an integration; matching requests replay the committed result.'],
  ['Deduplication', 'Signals', 'Recognizing an existing OPEN alert by integration/service/dedupKey instead of creating another alert.'],
  ['Grouping', 'Signals', 'Attaching eligible new alerts to an unresolved incident in the same service under a deterministic rule/window.'],
  ['Episode', 'Signals', 'An occurrence interval for an alert stream. episodeId and sourceSequence prevent stale recovery from closing newer occurrences.'],
  ['Priority', 'Response', 'An incident response ordering label. P1 is the highest priority in the current P1–P5 interface.'],
  ['ACK', 'Response', 'Acknowledgement of responsibility. It records the first ACK time and stops pending escalation without resolving the incident.'],
  ['On-call schedule', 'Response', 'Time-bound coverage assignments for a service. Current test routing uses static policy targets separately.'],
  ['Escalation', 'Response', 'Progression through notification targets while an incident remains unacknowledged.'],
  ['Backstop', 'Response', 'The final configured recipient after the two escalation levels exhaust their bounded budgets.'],
  ['Incident Commander', 'Response', 'An incident-specific coordination assignment; it does not grant missing account permissions.'],
  ['Evidence', 'Automation', 'Traceable observations or records supporting an investigation or action proposal.'],
  ['Hypothesis', 'Automation', 'An explanation that still needs verification. Correlation with a deployment is not proven causality.'],
  ['Runbook', 'Automation', 'An allowed procedure with defined parameters, scope and risk. The prototype simulates one fixed health inspection.'],
  ['Snapshot', 'Automation', 'The fixed action inputs and evidence that an approval refers to. Immutable enforcement is a backend requirement.'],
  ['Approval', 'Automation', 'An authorized decision on a specific action instance; it does not bypass quotas or other execution guards.'],
  ['UNKNOWN outcome', 'Automation', 'An execution may have started but its result is not confirmed. Reconcile before retrying.'],
  ['PIR', 'Learning', 'Post-Incident Review: a record progressing through Draft, In review, Approved and Completed.'],
  ['MTTA', 'Learning', 'Mean Time to Acknowledge: average creation-to-first-ACK duration over eligible incidents.'],
  ['MTTR', 'Learning', 'Mean Time to Resolve: average creation-to-resolution duration over eligible incidents.'],
  ['Audit trail', 'Learning', 'A history of actors and actions. Local demo records are not a production append-only audit store.'],
] as const;

export const helpQuestions = [
  ['Why can’t I sign in with the demo password?', 'Choose the intended sample account on Login. An Admin may have disabled it or changed its roles, and its password may have been changed locally. Use the current credentials or ask your workspace administrator.'],
  ['Why is my invitation rejected?', 'Check the invited email, code, 72-hour expiry and whether it has already been used or revoked. Resend invalidates the earlier code. Demo acceptance must use the same browser/origin where the invitation was created.'],
  ['Why did my session end?', 'Role changes, account disabling and password changes invalidate sessions in the demo. Sign in again with the current credentials; ask an Admin if the account is disabled.'],
  ['Why can I see an incident but not ACK or resolve it?', 'Reading and responding are different permissions. You need the response permission and responder/Commander assignment. ACK requires Triggered state; manual resolve requires Acknowledged state and a resolution reason.'],
  ['Why is the next escalation level not firing?', 'The current workspace has configuration and a Response preview, but no autonomous escalation timer or external paging. A local integration test routes to a static eligible Level 1 target.'],
  ['Why does my teammate not see my demo changes?', 'Workspace data is stored in your browser for one origin. Another browser, device or port uses a different local dataset. This version has no shared backend synchronization.'],
  ['Why can’t a Viewer read a draft review?', 'Viewer can read approved/completed PIRs. Draft and in-review material is limited to the permitted editors and reviewers.'],
  ['Does Run sandbox simulation affect my infrastructure?', 'No external command runs. The action state and incident history change locally. Real execution requires the backend guards and sandbox executor described in the MVP.'],
  ['Why is there no reset or password recovery email?', 'The active multi-role UI has no Reset sample data control or email recovery service. Contact the known workspace administrator for access help; do not rely on features shown in older screenshots.'],
] as const;

export const supportReportTemplate = `NexusOps issue report\n\nPage or route:\nRole used:\nIncident ID (if relevant):\nSteps to reproduce:\nExpected result:\nActual result:\nBrowser and approximate time:\n\nDo not include passwords, invitation codes, access tokens or sensitive customer data.`;
