import { Activity, BellRing, BookMarked, BookOpen, ClipboardCheck, History, LifeBuoy, PlayCircle, Route, ShieldCheck, Sparkles, type LucideIcon } from 'lucide-react';

export type ResourceMetadata = { key: string; group: 'Documentation' | 'Guides' | 'Resources'; title: string; description: string; icon: LucideIcon; badge?: string; audience: string; flow: string[] };

export const resourceDirectory: ResourceMetadata[] = [
  { key: 'product-documentation', group: 'Documentation', title: 'Product Documentation', description: 'Understand your workspace, connect its capabilities and find the right next step.', icon: BookOpen, audience: 'Everyone', flow: ['Receive signals', 'Own the response', 'Investigate', 'Review & learn'] },
  { key: 'mvp-scope', group: 'Documentation', title: 'MVP Scope', description: 'A precise view of what you can explore today and what the system is designed to support.', icon: Route, audience: 'Evaluators & builders', flow: ['One organization', 'One team', 'Scoped response', 'Human review'] },
  { key: 'roles-permissions', group: 'Documentation', title: 'Roles & Permissions', description: 'Know who can act, where they can act and how access is granted.', icon: ShieldCheck, audience: 'Admins & all team members', flow: ['Account role', 'Team scope', 'Assignment', 'Workflow state'] },
  { key: 'api-reference', group: 'Documentation', title: 'API Reference', description: 'The draft event contract and key management API requirements for the NexusOps MVP.', icon: Activity, badge: 'Draft', audience: 'Developers', flow: ['Authenticate', 'Validate event', 'Commit changes', 'Deliver updates'] },
  { key: 'incident-response', group: 'Guides', title: 'Incident Response', description: 'Move from an incoming incident to a recorded resolution with clear ownership at every step.', icon: BellRing, audience: 'Assigned Responders', flow: ['Triggered', 'Acknowledged', 'Investigate', 'Resolved'] },
  { key: 'on-call-operations', group: 'Guides', title: 'On-call Operations', description: 'Set service coverage, configure a bounded response policy and understand the handoff.', icon: Route, audience: 'Admins & Team Managers', flow: ['Service', 'Coverage', 'Policy', 'Test incident'] },
  { key: 'ai-investigation-automation', group: 'Guides', title: 'AI Investigation & Automation', description: 'Use evidence to assess a proposal and keep every execution decision accountable.', icon: Sparkles, audience: 'Assigned Responders', flow: ['Evidence', 'Hypothesis', 'Approval', 'Sandbox outcome'] },
  { key: 'post-incident-reviews', group: 'Guides', title: 'Post-Incident Reviews', description: 'Turn the response record into a reviewed explanation and follow-up work with an owner.', icon: ClipboardCheck, audience: 'Responders & reviewers', flow: ['Draft', 'In review', 'Approved', 'Completed'] },
  { key: 'incident-glossary', group: 'Resources', title: 'Incident Glossary', description: 'A shared vocabulary for signals, ownership, guarded actions and learning.', icon: BookMarked, audience: 'Everyone', flow: ['Signals', 'Response', 'Automation', 'Learning'] },
  { key: 'explore-demo', group: 'Resources', title: 'Explore the Demo', description: 'Choose a perspective and follow one incident through the NexusOps workspace.', icon: PlayCircle, audience: 'Everyone', flow: ['Choose a role', 'Sign in', 'Try a workflow', 'Review the outcome'] },
  { key: 'project-changelog', group: 'Resources', title: 'Project Changelog', description: 'Verified project milestones and the current documentation update.', icon: History, audience: 'Project followers', flow: ['Foundation', 'Workspace', 'Products', 'Documentation'] },
  { key: 'help-support', group: 'Resources', title: 'Help & Support', description: 'Troubleshoot access and demo behavior, then prepare clear details for your workspace administrator.', icon: LifeBuoy, audience: 'Everyone', flow: ['Identify the issue', 'Check role & scope', 'Collect safe details', 'Contact your Admin'] },
];
export const resourceGroups = ['Documentation', 'Guides', 'Resources'] as const;
