import { useState } from 'react';
import { ArrowDown, ArrowUp, Check, Eye, Layers, RotateCw } from 'lucide-react';
import { DEMO_ACCOUNT } from '../../demo/auth';
import { addDays, previewRotation, scheduleServices, scheduleZones, wallDate, wallTime } from './schedule';
import type { RotationRule, ScheduleInfo, Shift } from './schedule';
import './rotation.css';

export function RotationBuilder({ info, onInfo, members, shifts, onApply }: { info: ScheduleInfo; onInfo: (info: ScheduleInfo) => void; members: { id: string; name: string }[]; shifts: Shift[]; onApply: (shifts: Shift[], zone: ScheduleInfo['zone']) => void }) {
  const [name, setName] = useState(info.name);
  const [description, setDescription] = useState(info.description);
  const [zone, setZone] = useState(info.zone);
  const [rule, setRule] = useState<RotationRule>(() => ({ people: [members[0].id], service: 'payments-api', layer: 'Primary', startDate: addDays(wallDate(Date.now(), info.zone), 1), days: 14, cadence: 1, weekdays: [1, 2, 3, 4, 5, 6, 0], startTime: '09:00', endTime: '09:00', zone: info.zone }));
  const [preview, setPreview] = useState<Shift[] | null>(null);
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');
  function update(change: Partial<RotationRule>) { setRule(current => ({ ...current, ...change })); setPreview(null); setError(''); setMessage(''); }
  function reorder(index: number, direction: number) { const people = [...rule.people]; [people[index], people[index + direction]] = [people[index + direction], people[index]]; update({ people }); }
  function saveInfo() { if (!name.trim()) { setError('Enter a schedule name.'); return false; } onInfo({ name: name.trim(), description: description.trim(), zone }); return true; }
  return <section className="rt-builder">
    <div className="rt-heading"><div><span className="sc-eyebrow"><RotateCw size={14} /> BUILD YOUR COVERAGE</span><h3>Schedule & rotation settings</h3><p>Set a handover rhythm, then preview every shift before adding it.</p></div><span className="rt-badge">Planning draft</span></div>
    <form className="rt-info" onSubmit={event => { event.preventDefault(); if (saveInfo()) { setError(''); setMessage('Schedule details saved. Existing shift times are unchanged.'); } }}>
      <label>Schedule name<input required maxLength={100} value={name} onChange={event => setName(event.target.value)} /></label>
      <label>Team<input readOnly value={DEMO_ACCOUNT.team} aria-describedby="rt-team-hint" /></label>
      <label>Default timezone<select value={zone} onChange={event => { setZone(event.target.value as ScheduleInfo['zone']); update({ zone: event.target.value as ScheduleInfo['zone'] }); }}>{Object.keys(scheduleZones).map(value => <option key={value}>{value}</option>)}</select></label>
      <label className="rt-wide">Description <span>Optional</span><textarea maxLength={500} rows={2} value={description} onChange={event => setDescription(event.target.value)} placeholder="What does this schedule cover?" /></label>
      <p id="rt-team-hint">This workspace has one seeded team. Only its members can be included.</p><button type="submit" className="ws-button">Save schedule details</button>
    </form>
    <div className="rt-layer-heading"><Layers size={18} /><h4>Rotation layer</h4><span>Primary and Secondary are separate coverage layers, not escalation levels.</span></div>
    <div className="rt-columns">
      <div><h4><span>1</span>Choose responders</h4><p>Members rotate in the order below.</p><div className="rt-members">{members.map(member => <label key={member.id}><input type="checkbox" checked={rule.people.includes(member.id)} onChange={event => update({ people: event.target.checked ? [...rule.people, member.id] : rule.people.filter(id => id !== member.id) })} />{member.name}</label>)}</div><ol className="rt-order">{rule.people.map((id, index) => <li key={id}><span>{index + 1}</span><strong>{members.find(member => member.id === id)?.name}</strong><button aria-label={`Move ${members.find(member => member.id === id)?.name} earlier`} disabled={index === 0} onClick={() => reorder(index, -1)}><ArrowUp size={14} /></button><button aria-label={`Move ${members.find(member => member.id === id)?.name} later`} disabled={index === rule.people.length - 1} onClick={() => reorder(index, 1)}><ArrowDown size={14} /></button></li>)}</ol></div>
      <div><h4><span>2</span>Set rotation & hours</h4><label>Service<select value={rule.service} onChange={event => update({ service: event.target.value })}>{scheduleServices.map(service => <option key={service}>{service}</option>)}</select></label><div className="rt-pair"><label>Layer<select value={rule.layer} onChange={event => update({ layer: event.target.value as Shift['layer'] })}><option>Primary</option><option>Secondary</option></select></label><label>Rotate person every<select value={rule.cadence} onChange={event => update({ cadence: Number(event.target.value) as 1 | 7 })}><option value={1}>Day</option><option value={7}>7 days</option></select></label></div><fieldset><legend>Days with coverage</legend><div className="rt-days">{[{ n: 1, t: 'Mon' }, { n: 2, t: 'Tue' }, { n: 3, t: 'Wed' }, { n: 4, t: 'Thu' }, { n: 5, t: 'Fri' }, { n: 6, t: 'Sat' }, { n: 0, t: 'Sun' }].map(day => <button key={day.n} aria-pressed={rule.weekdays.includes(day.n)} onClick={() => update({ weekdays: rule.weekdays.includes(day.n) ? rule.weekdays.filter(n => n !== day.n) : [...rule.weekdays, day.n] })}>{day.t}</button>)}</div></fieldset><div className="rt-pair"><label>Start / handover<input type="time" value={rule.startTime} onChange={event => update({ startTime: event.target.value })} /></label><label>End<input type="time" value={rule.endTime} onChange={event => update({ endTime: event.target.value })} /></label></div><p>Same start/end means 24 hours. An earlier end means the following day. Weekday restrictions use the shift's start day.</p><button className="ws-text-button" onClick={() => update({ weekdays: [1, 2, 3, 4, 5, 6, 0], startTime: '09:00', endTime: '09:00' })}>Reset to all-day coverage</button></div>
      <div><h4><span>3</span>Choose the date range</h4><label>Start date<input type="date" value={rule.startDate} onChange={event => update({ startDate: event.target.value })} /></label><label>Generate coverage for<select value={rule.days} onChange={event => update({ days: Number(event.target.value) })}><option value={7}>7 days</option><option value={14}>14 days</option><option value={28}>28 days</option></select></label><div className="rt-explainer"><strong>A finite schedule, ready to review.</strong><p>People rotate by elapsed calendar days from the start date, including days excluded by restrictions. Weekly rotations change person every 7 days, at the chosen handover time.</p><p>Generated shifts can be edited individually. There is no background renewal; changing these settings only affects the next batch.</p></div></div>
    </div>
    <div className="rt-actions"><button className="ws-button" onClick={() => { const result = previewRotation({ ...rule, zone }, shifts, Date.now()); setError(result.error); setPreview(result.error ? null : result.shifts); setMessage(''); }}><Eye size={16} />Preview rotation</button><button className="ws-button ws-button-primary" disabled={!preview?.length} onClick={() => { const result = previewRotation({ ...rule, zone }, shifts, Date.now()); if (result.error) { setError(result.error); setPreview(null); return; } if (!saveInfo()) return; onApply(result.shifts.map(shift => ({ ...shift, id: crypto.randomUUID() })), zone); setPreview(null); setError(''); setMessage(`${result.shifts.length} shifts added. Review them in the calendar below.`); }}><Check size={16} />Add previewed shifts</button><span>Existing shifts are preserved. Overlaps block the entire batch.</span></div>
    {error && <p className="rt-error" role="alert">{error}</p>}<p className="rt-message" role="status">{message}</p>
    {preview && <div className="rt-preview"><h4>{preview.length} shifts · {zone}</h4><div className="rt-preview-scroll"><table><thead><tr><th>Responder</th><th>Starts</th><th>Ends</th><th>Layer</th></tr></thead><tbody>{preview.map(shift => <tr key={shift.id}><td>{members.find(member => member.id === shift.person)?.name}</td><td>{wallDate(shift.start, zone)} {wallTime(shift.start, zone)}</td><td>{wallDate(shift.end, zone)} {wallTime(shift.end, zone)}</td><td>{shift.layer}</td></tr>)}</tbody></table></div></div>}
  </section>;
}
