import { useState } from 'react';
import { Activity, ArrowRight, BarChart3, Check, Clock3, PlugZap, Server, ShieldCheck, X } from 'lucide-react';
import type { Incident } from './model';
import type { IntegrationConfig } from './system-config';
import './system-pages.css';

const services = ['payments-api', 'order-worker', 'auth-service'];

export function SystemPages({ view, incidents, integration, onIntegration, onNotice, onIncidents, now }: {
  view: 'status' | 'integrations' | 'analytics'; incidents: Incident[]; integration: IntegrationConfig;
  onIntegration: (value: IntegrationConfig) => void; onNotice: (message: string) => void; onIncidents: () => void; now: number;
}) {
  const [name, setName] = useState(integration.name);
  const [service, setService] = useState(integration.service);
  const [period, setPeriod] = useState(7);
  const recent = incidents.filter(item => item.createdAt >= now - period * 86400000);
  const ackTimes = recent.flatMap(item => item.acknowledgedAt ? [item.acknowledgedAt - item.createdAt] : []);
  const resolveTimes = recent.flatMap(item => item.resolvedAt ? [item.resolvedAt - item.createdAt] : []);
  const average = (values: number[]) => values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : null;
  const formatMinutes = (value: number | null) => value === null ? '—' : value < 60000 ? '<1m' : Math.round(value / 60000) + 'm';
  const hasIncidentData = recent.length > 0;

  if (view === 'status') {
    return <div className="sys-page"><div className="sys-intro"><div><span className="ws-kicker">CURRENT SERVICE HEALTH</span><h2>A quick read on your services.</h2><p>Status is inferred from open incidents in the sample workspace.</p></div><span className="sys-demo-tag"><Activity size={15} /> Demo data</span></div><div className="sys-status-grid">{services.map(serviceName => {
      const items = incidents.filter(item => item.service === serviceName);
      const triggered = items.filter(item => item.status === 'TRIGGERED').length;
      const acknowledged = items.filter(item => item.status === 'ACKNOWLEDGED').length;
      const status = triggered ? 'attention' : acknowledged ? 'investigating' : 'operational';
      const latest = [...items].sort((a, b) => b.createdAt - a.createdAt)[0];
      return <article className={'sys-status-card sys-' + status} key={serviceName}><div className="sys-status-head"><span><Server size={17} />{serviceName}</span><span className="sys-health"><i />{status === 'attention' ? 'Action needed' : status === 'investigating' ? 'Investigating' : 'Operational'}</span></div><div className="sys-status-summary"><strong>{triggered + acknowledged}</strong><span>open incidents</span><span className="sys-divider" /><span>{items.length} total in sample</span></div><div className="sys-status-meter"><i style={{ width: (items.length ? Math.max(12, 100 - (triggered * 35 + acknowledged * 12)) : 100) + '%' }} /></div><div className="sys-status-foot"><span>{latest ? 'Latest · #' + latest.id : 'No incidents recorded'}</span><button className="ws-text-button" onClick={onIncidents}>View incidents <ArrowRight size={14} /></button></div></article>;
    })}</div><div className="sys-note"><ShieldCheck size={17} /><p>This status view uses the demo incident list. It does not query live monitors, calculate SLA uptime or publish a customer-facing status page.</p></div></div>;
  }

  if (view === 'integrations') {
    return <div className="sys-page"><div className="sys-intro"><div><span className="ws-kicker">EVENT SOURCES</span><h2>Connect a monitoring source.</h2><p>Configure the demo intake for one service and test its local event path.</p></div><span className={'sys-demo-tag ' + (integration.connected ? 'is-connected' : '')}><PlugZap size={15} />{integration.connected ? 'Demo connected' : 'Not configured'}</span></div><div className="ws-panel sys-integration-card"><div className="sys-integration-heading"><span className="sys-integration-icon"><PlugZap size={22} /></span><div><span className="sys-tag">GENERIC EVENT INTAKE · MVP</span><h3>{integration.name || 'Monitoring webhook'}</h3><p>One integration can send events to one service in this demo.</p></div><span className={'sys-health ' + (integration.connected ? 'is-healthy' : 'is-paused')}><i />{integration.connected ? 'Enabled' : 'Not set up'}</span></div><form className="sys-integration-form" onSubmit={event => { event.preventDefault(); if (!name.trim()) return; onIntegration({ ...integration, name: name.trim(), service, connected: true }); onNotice('Demo integration settings saved. No API key was issued and no external endpoint was contacted.'); }}><label>Integration name<input required maxLength={80} value={name} onChange={event => setName(event.target.value)} placeholder="e.g. Production alerts" /></label><label>Target service<select value={service} onChange={event => setService(event.target.value)}>{services.map(value => <option key={value}>{value}</option>)}</select></label><button className="ws-button ws-button-primary" type="submit">{integration.connected ? 'Save settings' : 'Enable demo integration'} <ArrowRight size={15} /></button></form><div className="sys-integration-actions"><button className="ws-button" disabled={!integration.connected} onClick={() => { onIntegration({ ...integration, lastTestAt: Date.now() }); onNotice('Test event accepted by the local ' + integration.name + ' simulator for ' + integration.service + '.'); }}><Activity size={15} />Send test event</button><button className="ws-text-button" disabled={!integration.connected} onClick={() => onIntegration({ ...integration, connected: false })}><X size={14} />Pause</button>{integration.lastTestAt && <span>Last local test · {new Date(integration.lastTestAt).toLocaleTimeString()}</span>}</div></div><div className="sys-note"><ShieldCheck size={17} /><p>API keys, signed webhooks, retries and live vendor connectors are not implemented in this frontend prototype.</p></div></div>;
  }

  return <div className="sys-page"><div className="sys-intro"><div><span className="ws-kicker">RESPONSE PERFORMANCE</span><h2>See how your team responds.</h2><p>Metrics are calculated from the incident sample currently loaded in this workspace.</p></div><label className="sys-period">Reporting window<select value={period} onChange={event => setPeriod(Number(event.target.value))}><option value={1}>Last 24 hours</option><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option></select></label></div><div className="sys-metrics"><article><span><Activity size={16} />Incidents</span><strong>{hasIncidentData ? recent.length : '—'}</strong><small>in selected window</small></article><article><span><Clock3 size={16} />Avg. acknowledge time</span><strong>{formatMinutes(average(ackTimes))}</strong><small>{ackTimes.length} acknowledged samples</small></article><article><span><Check size={16} />Avg. resolution time</span><strong>{formatMinutes(average(resolveTimes))}</strong><small>{resolveTimes.length} resolved samples</small></article></div><div className="sys-analytics-grid"><section className="ws-panel sys-chart"><div><h3>Incidents by service</h3><span>{recent.length} total</span></div>{services.map(serviceName => { const count = recent.filter(item => item.service === serviceName).length; const max = Math.max(1, ...services.map(value => recent.filter(item => item.service === value).length)); return <div className="sys-bar-row" key={serviceName}><span>{serviceName}</span><div><i style={{ width: (count / max * 100) + '%' }} /></div><strong>{count}</strong></div>; })}{!hasIncidentData && <p>No incident samples fall in this period.</p>}</section><section className="ws-panel sys-chart"><div><h3>Response snapshot</h3><span>{period === 1 ? '24 hours' : period + ' days'}</span></div>{[['Triggered', recent.filter(item => item.status === 'TRIGGERED').length, 'sys-bar-red'], ['Acknowledged', recent.filter(item => item.status === 'ACKNOWLEDGED').length, 'sys-bar-amber'], ['Resolved', recent.filter(item => item.status === 'RESOLVED').length, 'sys-bar-green']].map(([label, count, tone]) => <div className="sys-bar-row" key={String(label)}><span>{label}</span><div><i className={String(tone)} style={{ width: (recent.length ? Number(count) / recent.length * 100 : 0) + '%' }} /></div><strong>{count}</strong></div>)}</section></div><div className="sys-note"><BarChart3 size={17} /><p>These sample counts and response times are illustrative. They are not an SLA report and do not include alerts outside the demo dataset.</p></div></div>;
}
