import { useNow } from './useNow';
import { useState } from 'react';
import { ArrowRight, Copy, Mail, ShieldCheck, Users } from 'lucide-react';
import { can, permissions, roleLabels, rolePermissions } from './policy';
import type { Role } from './policy';
import type { Command, Data, User } from './store';
export type Run = (command: Command) => boolean;
export function RolePicker({ roles, onChange }: { roles: Role[]; onChange: (roles: Role[]) => void }) {
  return <fieldset className="ac-role-picker"><legend>Assigned roles</legend>{(Object.keys(roleLabels) as Role[]).map(role => <label key={role}><input type="checkbox" checked={roles.includes(role)} onChange={event => onChange(event.target.checked ? role === 'VIEWER' ? ['VIEWER'] : [...roles.filter(r => r !== 'VIEWER'), role] : roles.filter(r => r !== role))} /><span>{roleLabels[role]}</span></label>)}</fieldset>;
}
export function PeopleAccess({ data, user, run }: { data: Data; user: User; run: Run }) {
  const now = useNow();
  const [tab, setTab] = useState('members'); const [query, setQuery] = useState(''); const [filter, setFilter] = useState('ALL');
  const [editing, setEditing] = useState<User | null>(null); const [invite, setInvite] = useState(false); const [email, setEmail] = useState(''); const [roles, setRoles] = useState<Role[]>(['RESPONDER']); const [copied, setCopied] = useState('');
  const manage = can(user, 'USER_MANAGE'); const team = data.users.filter(u => u.teamId === user.teamId);
  const visible = team.filter(u => `${u.name} ${u.email}`.toLowerCase().includes(query.toLowerCase()) && (filter === 'ALL' || u.roles.includes(filter as Role)));
  return <div className="ac-stack"><div className="ac-banner"><Users size={36}/><div><span className="ws-kicker">PLATFORM ENGINEERING</span><h2>One team. Clear responsibilities.</h2><p>{manage ? 'Invite colleagues and give each person the access their work needs.' : 'Find service owners, responders and your team manager.'}</p></div>{manage && <button className="ws-button ws-button-primary" onClick={() => setInvite(!invite)}><Mail size={16}/>Invite member</button>}</div>
    <div className="ac-tabs" role="group" aria-label="People view">{['members', ...(manage ? ['invitations', 'permissions'] : []), 'team'].map(t => <button key={t} aria-pressed={tab === t} onClick={() => setTab(t)}>{t}</button>)}</div>
    {invite && manage && <form className="ws-panel ac-card ac-form" onSubmit={event => { event.preventDefault(); if (run({ type: 'invite', email, roles })) { setEmail(''); setInvite(false); setTab('invitations'); } }}><h3>Invite to Platform Engineering</h3><p>Valid for 72 hours. This demo creates a code on this browser; no email is sent.</p><label>Work email<input type="email" required value={email} onChange={e => setEmail(e.target.value)}/></label><RolePicker roles={roles} onChange={setRoles}/><button className="ws-button ws-button-primary" disabled={!roles.length}>Create invitation <ArrowRight size={15}/></button></form>}
    {tab === 'members' && <section className="ws-panel ac-card"><div className="ac-toolbar"><input aria-label="Search members" placeholder="Search name or email…" value={query} onChange={e => setQuery(e.target.value)}/><select aria-label="Filter by role" value={filter} onChange={e => setFilter(e.target.value)}><option value="ALL">All roles</option>{Object.entries(roleLabels).map(([key, label]) => <option value={key} key={key}>{label}</option>)}</select><span>{visible.length} members</span></div><div className="ws-table-scroll"><table className="ws-table"><thead><tr><th>Member</th><th>Role</th><th>Team</th><th>Status</th>{manage && <th>Access</th>}</tr></thead><tbody>{visible.map(u => <tr key={u.id}><td><strong>{u.name}{u.id === user.id ? ' · You' : ''}</strong><small className="ac-subtext">{u.email}</small></td><td>{u.roles.map(r => <span className="ac-pill" key={r}>{roleLabels[r]}</span>)}</td><td>Platform Engineering</td><td><span className={`ac-pill ${u.enabled ? 'ac-green' : ''}`}>{u.enabled ? 'Active' : 'Disabled'}</span></td>{manage && <td><button className="ws-text-button" onClick={() => setEditing(structuredClone(u))}>Edit access</button></td>}</tr>)}</tbody></table></div>{!visible.length && <p className="ac-empty">No members match your filters.</p>}</section>}
    {editing && manage && <form className="ws-panel ac-card ac-form" onSubmit={event => { event.preventDefault(); if (run({ type: 'user', id: editing.id, roles: editing.roles, enabled: editing.enabled })) setEditing(null); }}><h3>Access for {editing.name}</h3><p>Existing sessions are invalidated after an access change. Transfer operational responsibilities before disabling an account.</p><RolePicker roles={editing.roles} onChange={roles => setEditing({ ...editing, roles })}/><label className="ac-check"><input type="checkbox" checked={editing.enabled} onChange={e => setEditing({ ...editing, enabled: e.target.checked })}/>Account enabled</label><div className="ac-toolbar"><button className="ws-button ws-button-primary">Save access</button><button type="button" className="ws-button" onClick={() => setEditing(null)}>Cancel</button></div></form>}
    {tab === 'invitations' && manage && <section className="ws-panel ac-card"><h3>Invitations</h3><p>Share the code with the invitee, then use Join your team on this browser. Resending invalidates the previous code.</p>{data.invitations.filter(i => i.teamId === user.teamId).map(i => <article className="ac-list-row" key={i.id}><div><strong>{i.email}</strong><small className="ac-subtext">{i.roles.map(r => roleLabels[r]).join(' + ')} · expires {new Date(i.expiresAt).toLocaleString()}</small>{i.status === 'PENDING' && i.expiresAt > now && <code className="ac-code">{i.token}</code>}</div><span className="ac-pill">{i.status === 'PENDING' && i.expiresAt <= now ? 'EXPIRED' : i.status}</span>{i.status === 'PENDING' && <div className="ac-toolbar"><button className="ws-button" disabled={i.expiresAt <= now} onClick={async () => { try { await navigator.clipboard.writeText(i.token); setCopied(i.id); } catch { setCopied('unavailable'); } }}><Copy size={14}/>{copied === i.id ? 'Copied' : 'Copy code'}</button><button className="ws-text-button" onClick={() => run({ type: 'invitation', id: i.id, operation: 'resend' })}>Resend</button><button className="ws-text-button" onClick={() => run({ type: 'invitation', id: i.id, operation: 'revoke' })}>Revoke</button></div>}</article>)}{!data.invitations.length && <div className="ac-empty"><Mail size={26}/><p>No invitations yet. Invite your first colleague above.</p></div>}{copied === 'unavailable' && <p role="status">Clipboard unavailable. Select and copy the visible code.</p>}</section>}
    {tab === 'permissions' && manage && <section className="ws-panel ac-card"><h3>Fixed role permissions</h3><p>Permissions combine across assigned roles. Incident actions also require incident assignment and valid lifecycle state.</p><div className="ws-table-scroll"><table className="ws-table"><thead><tr><th>Permission</th>{Object.values(roleLabels).map(r => <th key={r}>{r}</th>)}</tr></thead><tbody>{permissions.map(p => <tr key={p}><td>{p}</td>{Object.keys(roleLabels).map(r => <td key={r}>{rolePermissions[r as Role].includes(p) ? '✓' : '—'}</td>)}</tr>)}</tbody></table></div></section>}
    {tab === 'team' && <section className="ws-panel ac-card"><ShieldCheck size={27}/><h3>Platform Engineering</h3><p>One organization · one team. Team membership defines the shared operational scope in this MVP.</p><div className="ac-metrics"><article><strong>{team.filter(u => u.enabled).length}</strong><span>active members</span></article><article><strong>{data.services.filter(s => s.teamId === user.teamId).length}</strong><span>owned services</span></article><article><strong>{team.filter(u => can(u, 'INCIDENT_ACK')).length}</strong><span>eligible responders</span></article></div><p>Incident Commander is assigned per incident. It does not grant account administration.</p></section>}
  </div>;
}
