import { useNow } from './useNow';
import { useState } from 'react';
import { Activity, ArrowRight, Bell, CalendarDays, Check, ChevronRight, ClipboardList, GitBranch, LogOut, Server, ShieldCheck, Sparkles, Users, X } from 'lucide-react';
import { can, roleLabels } from './policy';
import type { Permission } from './policy';
import { currentUser, dispatch, useData } from './store';
import type { Command, Data, User } from './store';
import { PeopleAccess } from './PeopleAccess';
import { AuditPage, ProfilePage } from './ProfileAudit';
import { IntegrationsView, PolicyView, ScheduleView, ServicesPage } from './Configuration';
import { IncidentsView, ReviewsView } from './Operations';
import '../responder/responder.css';
import '../responder/workspace-pages.css';
import './workspace.css';

const pages = {
  overview: ['Overview', 'READ'], incidents: ['Incidents', 'READ'], services: ['Services', 'READ'], people: ['People & access', 'PEOPLE_VIEW'],
  schedule: ['On-call schedule', 'READ'], escalation: ['Escalation policies', 'READ'], integrations: ['Integrations', 'INTEGRATION_MANAGE'],
  status: ['Service status', 'READ'], analytics: ['Analytics', 'READ'], reviews: ['Post-incident reviews', 'READ'], automation: ['Automation', 'AUTOMATION_EXECUTE'], audit: ['Audit trail', 'AUDIT_VIEW'], profile: ['Your profile', 'READ'], inbox: ['Your inbox', 'READ'], setup: ['Account setup', 'READ'],
} as const satisfies Record<string, readonly [string, Permission]>;
type Page = keyof typeof pages;
function setupSteps(data: Data, user: User, now: number): { title: string; description: string; page: Page; done: boolean }[] {
  const own = { title: 'Complete your profile', description: 'Add your role at work and a contact number.', page: 'profile' as Page, done: !!user.title && !!user.phone };
  if (can(user, 'SERVICE_MANAGE')) return [own,
    ...(can(user, 'INVITATION_MANAGE') ? [{ title: 'Invite a colleague', description: 'Assign fixed roles and share an invitation code.', page: 'people' as Page, done: data.invitations.some(i => i.status === 'ACCEPTED') }] : []),
    { title: 'Review service ownership', description: 'Describe your services and dependencies.', page: 'services', done: data.services.every(s => !!s.description) },
    { title: 'Plan on-call coverage', description: 'Assign explicit hours to eligible responders.', page: 'schedule', done: data.shifts.some(s => s.end > now) },
    { title: 'Review escalation policies', description: 'Two levels and a final backstop for each service.', page: 'escalation', done: data.services.filter(s => s.enabled).every(s => data.policies.some(p => p.service === s.name && p.version > 1)) },
    { title: 'Connect and test an integration', description: 'Create a local test incident and notification.', page: 'integrations', done: data.integrations.some(i => i.enabled && !!i.lastTestAt) }];
  if (can(user, 'INCIDENT_ACK')) return [own, { title: 'Check your on-call assignment', description: 'Your manager assigns shifts; review your upcoming coverage.', page: 'schedule', done: data.shifts.some(s => s.person === user.id && s.end > now) }, { title: 'Respond to an assigned incident', description: 'Acknowledge when you accept responsibility.', page: 'incidents', done: data.audit.some(a => a.actor === user.name && a.action === 'INCIDENT_ACK') }];
  return [own];
}
export function Workspace({ onLogout }: { onLogout: () => void }) {
  const now = useNow();
  const data = useData(); const user = currentUser(data);
  const [message, setMessage] = useState(''); const [failed, setFailed] = useState(false); const [initialId, setInitialId] = useState<number | null>(null);
  if (!user) return null;
  const raw = window.location.hash.split('/')[1] || (can(user, 'SERVICE_MANAGE') || !can(user, 'INCIDENT_ACK') ? 'overview' : 'incidents');
  const page = Object.hasOwn(pages, raw) ? raw as Page : null;
  const allowed = page && can(user, pages[page][1]);
  const steps = setupSteps(data, user, now); const remaining = steps.filter(s => !s.done).length;
  const role = user.roles.map(r => roleLabels[r]).join(' + '); const notices = data.notices.filter(n => n.userId === user.id); const unread = notices.filter(n => !n.read).length;
  function navigate(next: Page) { window.location.hash = `workspace/${next}`; setMessage(''); setInitialId(null); }
  function openIncident(id: number) { navigate('incidents'); setInitialId(id); }
  function run(command: Command) { try { dispatch(command); setMessage(command.type === 'test-event' ? 'Local test incident created. The assigned responder has a new inbox notification.' : 'Changes saved in this browser.'); setFailed(false); return true; } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to save.'); setFailed(true); return false; } }
  return <div className="ws-app ac-workspace"><div className="ws-demo-bar"><span><span className="ws-demo-dot"/>DEMO WORKSPACE</span><p>Shared browser data · simulated authentication · no live paging</p><span className="ws-demo-role">{role}</span></div>
    {remaining > 0 && <div className="ws-onboarding-bar"><span>{remaining} setup {remaining === 1 ? 'step' : 'steps'} remaining for your account</span><button className="ws-onboarding-button" onClick={() => navigate('setup')}>Complete onboarding <ChevronRight size={14}/></button></div>}
    <header className="ws-header"><button className="ws-brand" aria-label="Go to your workspace home" onClick={() => navigate(can(user, 'SERVICE_MANAGE') || !can(user, 'INCIDENT_ACK') ? 'overview' : 'incidents')}>Nexus<span>Ops</span></button><nav aria-label="Workspace navigation">{(['overview', 'incidents', 'services', 'people', 'integrations', 'analytics'] as Page[]).filter(p => can(user, pages[p][1])).map(p => <button key={p} aria-current={page === p ? 'page' : undefined} onClick={() => navigate(p)}>{p === 'people' ? 'People' : pages[p][0]}</button>)}</nav><div className="ws-header-account"><button className={`ws-icon-button ws-bell ${unread ? 'has-unread' : ''}`} aria-label={`Open inbox, ${unread} unread`} onClick={() => navigate('inbox')}><Bell size={19}/>{unread > 0 && <span className="ws-bell-count">{unread}</span>}</button><button className="ws-user" onClick={() => navigate('profile')}>{user.avatar ? <img className="ws-avatar" src={user.avatar} alt=""/> : <span className="ws-avatar">{user.name.split(' ').map(n => n[0]).slice(0, 2).join('')}</span>}<div><strong>{user.name}</strong><small>{role}</small></div></button><button className="ws-icon-button" aria-label="Log out" onClick={onLogout}><LogOut size={18}/></button></div></header>
    <div className="ac-subnav" aria-label="Operational tools">{(['schedule', 'escalation', 'status', 'reviews', 'automation', 'audit'] as Page[]).filter(p => can(user, pages[p][1])).map(p => <button key={p} aria-current={page === p ? 'page' : undefined} onClick={() => navigate(p)}>{pages[p][0]}</button>)}</div>
    <main className="ws-main"><div className="ws-breadcrumb">Platform Engineering <ChevronRight size={13}/>{page ? pages[page][0] : 'Page not found'}</div><div className="ws-heading"><div><span className="ws-kicker">{can(user, 'USER_MANAGE') ? 'WORKSPACE ADMINISTRATION' : can(user, 'SERVICE_MANAGE') ? 'TEAM OPERATIONS' : can(user, 'INCIDENT_ACK') ? 'YOUR RESPONSE WORKSPACE' : 'TEAM VISIBILITY'}</span><h1>{page ? pages[page][0] : 'Page not found'}</h1><p>{page === 'overview' ? 'A shared view of service health, response and the work that needs attention.' : 'Your team, services and response tools, connected in one workspace.'}</p></div><span className="ws-scope"><ShieldCheck size={15}/>{user.roles.includes('VIEWER') ? 'Read-only operations' : role}</span></div>
    {message && <div className={`ac-feedback ${failed ? 'ac-error' : ''}`} role={failed ? 'alert' : 'status'}><span>{message}</span><button aria-label="Dismiss message" onClick={() => setMessage('')}><X size={16}/></button></div>}
    {!allowed ? <section className="ws-panel ac-card ac-empty"><ShieldCheck size={32}/><h2>{page ? 'This page requires additional access' : 'Page not found'}</h2><p>Your current roles do not grant access to this destination.</p><button className="ws-button" onClick={() => navigate('overview')}>Return to overview</button></section> : <div key={page} className="ac-page-enter">
      {page === 'overview' && <Overview data={data} user={user} navigate={navigate} onIncident={openIncident}/>}
      {page === 'incidents' && <IncidentsView data={data} user={user} run={run} initialId={initialId} onCloseInitial={() => setInitialId(null)} message={message}/>}
      {page === 'people' && <PeopleAccess data={data} user={user} run={run}/>}
      {page === 'services' && <ServicesPage data={data} user={user} run={run}/>}
      {page === 'schedule' && <ScheduleView data={data} user={user} run={run}/>}
      {page === 'escalation' && <PolicyView data={data} user={user} run={run}/>}
      {page === 'integrations' && <IntegrationsView data={data} user={user} run={run}/>}
      {(page === 'status' || page === 'analytics') && <Health data={data} user={user} analytics={page === 'analytics'} onIncident={openIncident}/>}
      {page === 'reviews' && <ReviewsView data={data} user={user} run={run}/>}
      {page === 'audit' && <AuditPage data={data} user={user}/>}
      {page === 'profile' && <ProfilePage user={user} run={run} onLogout={onLogout}/>}
      {page === 'automation' && <section className="ws-panel ac-card"><h2><Sparkles size={23}/>Automation center</h2><p>Review proposals in incident context. Only assigned responders or commanders with permission can decide and simulate execution.</p>{data.actions.filter(a => data.incidents.some(i => i.id === a.incidentId && i.teamId === user.teamId)).map(a => <div className="ac-list-row" key={a.id}><strong>Service health inspection · #{a.incidentId}</strong><span className="ac-pill">{a.state}</span><button className="ws-text-button" onClick={() => openIncident(a.incidentId)}>Review incident <ArrowRight size={14}/></button></div>)}{!data.actions.length && <div className="ac-empty"><p>No proposals yet. Open an assigned incident to generate a sample investigation and propose a sandbox action.</p><button className="ws-button" onClick={() => navigate('incidents')}>Open incidents</button></div>}</section>}
      {page === 'inbox' && <section className="ws-panel ac-card"><div className="ac-between"><h2>{unread} unread notifications</h2><button className="ws-text-button" disabled={!unread} onClick={() => run({ type: 'read' })}>Mark all as read</button></div>{notices.map(n => <div className="ac-list-row" key={n.id}><Bell size={18}/><div><strong>{n.text}</strong><small className="ac-subtext">{n.read ? 'Read' : 'Unread'}</small></div>{n.incidentId && <button className="ws-text-button" onClick={() => { run({ type: 'read', id: n.id }); openIncident(n.incidentId!); }}>Open incident</button>}{!n.read && <button className="ws-icon-button" aria-label="Mark notification read" onClick={() => run({ type: 'read', id: n.id })}><Check size={16}/></button>}</div>)}{!notices.length && <p className="ac-empty">You have no notifications yet.</p>}<p>Reading a notification does not acknowledge its incident.</p></section>}
      {page === 'setup' && <section className="ws-panel ac-card"><h2>Set up your workspace</h2><p>{steps.length - remaining}/{steps.length} complete · checklist tailored to your permissions</p><div className="ac-progress"><span style={{ width: `${100 * (steps.length - remaining) / steps.length}%` }}/></div>{steps.map(s => <div className="ac-list-row" key={s.title}><span className="ac-number">{s.done ? <Check size={18}/> : <ChevronRight size={18}/>}</span><div><strong>{s.title}</strong><p>{s.description}</p></div><button className="ws-button" onClick={() => navigate(s.page)}>{s.done ? 'Review' : 'Continue'}<ArrowRight size={14}/></button></div>)}</section>}
    </div>}
    <footer className="ws-footer"><span>NexusOps · Platform Engineering</span><span>Role-scoped frontend demo · backend authorization pending</span><button className="ws-text-button" onClick={() => navigate('profile')}>Your access</button></footer></main>
  </div>;
}

function Overview({ data, user, navigate, onIncident }: { data: Data; user: User; navigate: (page: Page) => void; onIncident: (id: number) => void }) {
  const now = useNow();
  const incidents = data.incidents.filter(i => i.teamId === user.teamId); const active = incidents.filter(i => i.status !== 'RESOLVED'); const services = data.services.filter(s => s.teamId === user.teamId);
  const admin = can(user, 'USER_MANAGE'); const manager = can(user, 'SERVICE_MANAGE');
  return <div className="ac-stack"><div className="ac-hero"><div><span className="ws-kicker">{admin ? 'ACCOUNT ADMIN' : manager ? 'TEAM MANAGER' : 'YOUR TEAM AT A GLANCE'}</span><h2>{admin ? 'Keep your workspace ready.' : manager ? 'Clarity for the team. Confidence for the next shift.' : 'Stay close to what matters.'}</h2><p>{admin ? 'Manage access, review configuration and follow the decisions behind every response.' : manager ? 'Connect service ownership, on-call coverage and escalation so the team knows who responds next.' : 'Follow incident progress and service health across Platform Engineering.'}</p><button className="ws-button ws-button-primary" onClick={() => navigate(admin ? 'people' : manager ? 'schedule' : 'incidents')}>{admin ? 'Manage people & access' : manager ? 'Plan coverage' : 'View incidents'}<ArrowRight size={16}/></button></div><div className="ac-orbit" aria-label="Services connect to people and incident response"><div className="ac-orbit-center"><ShieldCheck size={35}/><strong>NexusOps</strong></div><span className="ac-orbit-a"><Server size={23}/>Services</span><span className="ac-orbit-b"><Users size={23}/>People</span><span className="ac-orbit-c"><Activity size={23}/>Response</span><svg viewBox="0 0 320 250" aria-hidden="true"><path d="M160 125L58 48M160 125L267 61M160 125L190 216" fill="none" stroke="#9bceb5" strokeWidth="2" strokeDasharray="4 6"/><circle cx="160" cy="125" r="90" fill="none" stroke="#d2e9dc"/></svg></div></div>
    <div className="ac-metrics">{[{ label: 'Open incidents', value: active.length, page: 'incidents' as Page }, { label: 'Awaiting ACK', value: active.filter(i => i.status === 'TRIGGERED').length, page: 'incidents' as Page }, { label: 'Enabled services', value: services.filter(s => s.enabled).length, page: 'services' as Page }, { label: admin ? 'Pending invitations' : 'Upcoming shifts', value: admin ? data.invitations.filter(i => i.status === 'PENDING' && i.expiresAt > now).length : data.shifts.filter(s => s.end > now).length, page: admin ? 'people' as Page : 'schedule' as Page }].map(m => <button className="ws-panel" key={m.label} onClick={() => navigate(m.page)}><strong>{m.value}</strong><span>{m.label}<ArrowRight size={14}/></span></button>)}</div>
    <div className="ac-two"><section className="ws-panel ac-card"><div className="ac-between"><h3>Needs attention</h3><Activity size={20}/></div>{active.sort((a, b) => a.priority.localeCompare(b.priority)).slice(0, 5).map(i => <button className="ac-list-row ac-row-button" key={i.id} onClick={() => onIncident(i.id)}><span className={`ws-priority ws-${i.priority.toLowerCase()}`}>{i.priority}</span><div><strong>{i.title}</strong><small className="ac-subtext">{i.service} · {i.assignedName}</small></div><ChevronRight size={18}/></button>)}{!active.length && <p className="ac-empty">No open incidents.</p>}</section><section className="ws-panel ac-card"><h3>{manager ? 'Configuration readiness' : 'Response context'}</h3>{services.map(s => <div className="ac-list-row" key={s.id}><Server size={18}/><div><strong>{s.name}</strong><small className="ac-subtext">{data.policies.some(p => p.service === s.name) ? 'Policy ready' : 'Policy missing'} · {data.shifts.some(v => v.service === s.name && v.end > now) ? 'Coverage planned' : 'No upcoming shifts'}</small></div></div>)}<button className="ws-text-button" onClick={() => navigate('setup')}>Review account setup <ArrowRight size={14}/></button></section></div>
    {admin && <section className="ws-panel ac-card"><h3><ClipboardList size={18}/>Recent access and configuration changes</h3>{data.audit.slice(0, 4).map(a => <div className="ac-list-row" key={a.id}><span>{a.actor}</span><strong>{a.action}</strong><span>{a.resource}</span></div>)}<button className="ws-text-button" onClick={() => navigate('audit')}>Open audit trail <ArrowRight size={14}/></button></section>}
  </div>;
}

function Health({ data, user, analytics, onIncident }: { data: Data; user: User; analytics: boolean; onIncident: (id: number) => void }) {
  const now = useNow();
  const [period, setPeriod] = useState(7); const incidents = data.incidents.filter(i => i.teamId === user.teamId && (!analytics || i.createdAt >= now - period * 86400000));
  const ack = incidents.flatMap(i => i.acknowledgedAt === null ? [] : [i.acknowledgedAt - i.createdAt]); const resolve = incidents.flatMap(i => i.resolvedAt === null ? [] : [i.resolvedAt - i.createdAt]);
  const mean = (samples: number[]) => samples.length ? `${Math.round(samples.reduce((a, b) => a + b, 0) / samples.length / 60000)}m` : '—';
  return <div className="ac-stack">{analytics && <><div className="ac-toolbar"><CalendarDays size={18}/><label>Reporting window <select value={period} onChange={e => setPeriod(Number(e.target.value))}><option value={1}>24 hours</option><option value={7}>7 days</option><option value={30}>30 days</option></select></label></div><div className="ac-metrics"><article className="ws-panel"><strong>{incidents.length}</strong><span>Incidents in window</span></article><article className="ws-panel"><strong>{mean(ack)}</strong><span>MTTA · {ack.length} acknowledged samples</span></article><article className="ws-panel"><strong>{mean(resolve)}</strong><span>MTTR · {resolve.length} resolved samples</span></article></div></>}
    <div className="ac-grid">{data.services.filter(s => s.teamId === user.teamId).map(s => { const rows = incidents.filter(i => i.service === s.name); const open = rows.filter(i => i.status !== 'RESOLVED'); return <section className="ws-panel ac-card" key={s.id}><div className="ac-between"><Server size={25}/><span className="ac-pill">{!s.enabled ? 'Disabled' : open.length ? 'Active incidents' : 'No open incidents'}</span></div><h3>{s.name}</h3><div className="ac-health-count">{analytics ? rows.length : open.length}<small>{analytics ? 'incidents in window' : 'open incidents'}</small></div>{analytics && <div className="ac-progress"><span style={{ width: `${incidents.length ? rows.length / incidents.length * 100 : 0}%` }}/></div>}{open.slice(0, 3).map(i => <button className="ac-list-row ac-row-button" key={i.id} onClick={() => onIncident(i.id)}><span>#{i.id} {i.title}</span><ArrowRight size={14}/></button>)}</section>; })}</div><p className="ac-callout"><GitBranch size={17}/>Calculated from local incidents. This view does not measure live uptime or publish a public status page.</p></div>;
}
